name: Build and Deploy

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build
        run: ./build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Get Release ID
        id: get_release_id
        run: echo "RELEASE_ID=${{ steps.create_release.outputs.release_id }}" >> $GITHUB_ENV

      - name: Attach android amd64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-android-amd64.exe
          asset_name: evanotebook-relay-android-amd64.exe
          asset_content_type: application/octet-stream
      - name: Attach android arm64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-android-arm64.exe
          asset_name: evanotebook-relay-android-arm64.exe
          asset_content_type: application/octet-stream
      - name: Attach darwin amd64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-darwin-amd64.exe
          asset_name: evanotebook-relay-darwin-amd64.exe
          asset_content_type: application/octet-stream
      - name: Attach darwin arm64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-darwin-arm64.exe
          asset_name: evanotebook-relay-darwin-arm64.exe
          asset_content_type: application/octet-stream
      - name: Attach freebsd 386 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-freebsd-386.exe
          asset_name: evanotebook-relay-freebsd-386.exe
          asset_content_type: application/octet-stream
      - name: Attach freebsd amd64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-freebsd-amd64.exe
          asset_name: evanotebook-relay-freebsd-amd64.exe
          asset_content_type: application/octet-stream
      - name: Attach freebsd arm Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-freebsd-arm.exe
          asset_name: evanotebook-relay-freebsd-arm.exe
          asset_content_type: application/octet-stream
      - name: Attach freebsd arm64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-freebsd-arm64.exe
          asset_name: evanotebook-relay-freebsd-arm64.exe
          asset_content_type: application/octet-stream
      - name: Attach freebsd riscv64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-freebsd-riscv64.exe
          asset_name: evanotebook-relay-freebsd-riscv64.exe
          asset_content_type: application/octet-stream
      - name: Attach linux 386 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-386.exe
          asset_name: evanotebook-relay-linux-386.exe
          asset_content_type: application/octet-stream
      - name: Attach linux amd64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-amd64.exe
          asset_name: evanotebook-relay-linux-amd64.exe
          asset_content_type: application/octet-stream
      - name: Attach linux arm Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-arm.exe
          asset_name: evanotebook-relay-linux-arm.exe
          asset_content_type: application/octet-stream
      - name: Attach linux arm64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-arm64.exe
          asset_name: evanotebook-relay-linux-arm64.exe
          asset_content_type: application/octet-stream
      - name: Attach linux mips Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-mips.exe
          asset_name: evanotebook-relay-linux-mips.exe
          asset_content_type: application/octet-stream
      - name: Attach linux mips64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-mips64.exe
          asset_name: evanotebook-relay-linux-mips64.exe
          asset_content_type: application/octet-stream
      - name: Attach linux mips64le Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-mips64le.exe
          asset_name: evanotebook-relay-linux-mips64le.exe
          asset_content_type: application/octet-stream
      - name: Attach linux ppc64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-ppc64.exe
          asset_name: evanotebook-relay-linux-ppc64.exe
          asset_content_type: application/octet-stream
      - name: Attach linux riscv64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-riscv64.exe
          asset_name: evanotebook-relay-linux-riscv64.exe
          asset_content_type: application/octet-stream
      - name: Attach windows 386 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-windows-386.exe
          asset_name: evanotebook-relay-windows-386.exe
          asset_content_type: application/octet-stream
      - name: Attach windows amd64 Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-windows-amd64.exe
          asset_name: evanotebook-relay-windows-amd64.exe
          asset_content_type: application/octet-stream
      - name: Attach windows arm Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-windows-arm.exe
          asset_name: evanotebook-relay-windows-arm.exe
          asset_content_type: application/octet-stream
