name: Build and Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o evanotebook-relay-windows-amd64.exe

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o evanotebook-relay-linux-amd64

      - name: Create Release
        id: create_release
        uses: actions/create-a-release-in-a-github-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: evanotebook-relay-windows
          path: evanotebook-relay-windows-amd64.exe

      - name: Upload Linux Build
        uses: actions/upload-artifact@v2
        with:
          name: evanotebook-relay-linux
          path: evanotebook-relay-linux-amd64

      - name: Get Release ID
        id: get_release_id
        run: echo "RELEASE_ID=${{ steps.create_release.outputs.release_id }}" >> $GITHUB_ENV

      - name: Download Windows Build
        uses: actions/download-artifact@v2
        with:
          name: evanotebook-relay-windows
          path: evanotebook-relay-windows-amd64.exe

      - name: Download Linux Build
        uses: actions/download-artifact@v2
        with:
          name: evanotebook-relay-linux
          path: evanotebook-relay-linux-amd64

      - name: Attach Windows Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-windows-amd64.exe
          asset_name: evanotebook-relay-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Attach Linux Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: evanotebook-relay-linux-amd64
          asset_name: evanotebook-relay-linux-amd64
          asset_content_type: application/octet-stream